### ISSUE TITLE
如果source和target的数目不一样，该怎么一起训练呢？

### ISSUE THREAD

**Issue by zzy99** [Daipuwei/DANN-MNIST#1]
比如source有10000条，target只有1000条，那么是一起只训练1000条，还是每一步中按比例呢？

**Comment by Daipuwei** [comment]
你可以分别写个源域数据生成器和目标域数据生成器，在每次迭代过程中依次生成每个小批次源域和目标域数据集，但是要在遍历一次数据集时做好随机打乱整个数据集操作。

或者你可以先做离线的数据增强，将目标域数据集和源域数据集扩充到相同规模，然后统一用一个生成器来读取小批量源域和目标域数据集

**Comment by Daipuwei** [comment]
如有需要可以添加微信进行交流。微信号为：dpw19960712
